CC = g++
CFLAGS = -std=c++11 -Os -I src -I benchmarks/src
TOUCHSTONE = src
BENCHMARKS = benchmarks/src

no-target:
	@echo -e "Target unspecified:\n\
	\tlarge: Compiles large json benchmark.\n\
	\tclean: Removes all files generated by the makefile."

mkbin:
	@if [ ! -e bin ];\
	then echo -e "Creating bin directory..." && mkdir bin && echo -e "\e[32mSuccess.\e[0m";\
	fi

large: mkbin
	@echo -e "Compiling large json benchmark..."
	@if command -v  $(CC) &> /dev/null;\
	then if $(CC) $(CFLAGS) $(BENCHMARKS)/large.cc $(BENCHMARKS)/file_map.cc $(TOUCHSTONE)/*.cc -o bin/large.out &> /dev/null;\
		then echo -e "\e[32mSuccess.\e[0m";\
		else echo -e "\e[91mFailure.\e[0m";\
		fi;\
	else echo -e "\e[1m\e[91m$(CC) required.\e[0m";\
	fi

clean:
	@echo -e "Removing generated files..."
	@if [ -e bin/* ] && rm bin/*;\
	then echo -e "\e[32mSuccess.\e[0m";\
	else echo -e "\e[35mNo files to remove.\e[0m";\
	fi
