CC = g++
CFLAGS = -std=c++17 -O2 -I src
TOUCHSTONE = src
BENCHMARKS = benchmarks/src

no-target:
	@echo -e "Target unspecified:\n\
	\tlarge: Compiles large json benchmark.\n\
	\tclean: Removes any files generated by the makefile."

large:
	@echo "Compiling large json benchmark..."
	@if command -v  $(CC) &> /dev/null; then\
		if $(CC) $(CFLAGS) $(BENCHMARKS)/large.cpp $(TOUCHSTONE)/*.cpp -o large.out &> /dev/null; then\
			echo "Compile was successful.";\
		else\
			echo "Compile was unsuccessful.";\
		fi;\
	else\
		echo "$(CC) is required to proceed.";\
	fi

clean:
	@echo "Removing generated files..."
	@if [ -e large.out ] && rm large.out;\
	then echo "Generated file(s) removed.";\
	else echo "No generated files to remove.";\
	fi
